image: ghcr.io/cirruslabs/android-sdk:35

stages:
  - build

build_apk:
  stage: build
  script:
    - cd android/TrendScope
    - chmod +x gradlew
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - android/TrendScope/app/build/outputs/apk/release/app-release.apk
    expire_in: 7 days
