image: ghcr.io/cirruslabs/android-sdk:35

stages:
  - build

build_apk:
  stage: build
  script:
    - cd android/TrendScope
    - chmod +x gradlew
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - android/TrendScope/app/build/outputs/apk/debug/app-debug.apk
    expire_in: 7 days