release_github:
  stage: release
  tags:
    - android

  needs:
    - build_apk

  script:
    - |
      $ErrorActionPreference = "Stop"

      $version = (Select-String -Path "android/TrendScope/app/build.gradle.kts" -Pattern 'versionName = "(.*)"').Matches.Groups[1].Value

      Write-Host "Version: $version"
      Write-Host "Username: '$env:GITHUB_USERNAME'"
      Write-Host "Repository: '$env:GITHUB_REPOSITORY'"
      Write-Host "Token Present: $(-not [string]::IsNullOrWhiteSpace($env:GITHUB_TOKEN))"

      $repo = "$env:GITHUB_USERNAME/$env:GITHUB_REPOSITORY"

      Write-Host "Repo: '$repo'"

      $headers = @{
        Authorization = "token $env:GITHUB_TOKEN"
        Accept        = "application/vnd.github+json"
      }

      try {
        $release = Invoke-RestMethod `
          -Headers $headers `
          -Uri "https://api.github.com/repos/$repo/releases/tags/v$version" `
          -Method Get

        Write-Host "Existing release found."
      }
      catch {
        Write-Host "Creating new release..."

        $release = Invoke-RestMethod `
          -Headers $headers `
          -Uri "https://api.github.com/repos/$repo/releases" `
          -Method Post `
          -ContentType "application/json" `
          -Body (@{
              tag_name = "v$version"
              name = "TrendScope v$version"
              generate_release_notes = $true
          } | ConvertTo-Json)
      }

      Write-Host "Release ID: $($release.id)"
      Write-Host "Raw Upload URL: $($release.upload_url)"

      $uploadUrl = $release.upload_url -replace '\{\?name,label\}', ''

      Write-Host "Clean Upload URL: $uploadUrl"

      if (-not ($uploadUrl -match '^https://')) {
          throw "Invalid upload URL: $uploadUrl"
      }

      $assets = Invoke-RestMethod `
        -Headers $headers `
        -Uri "https://api.github.com/repos/$repo/releases/$($release.id)/assets" `
        -Method Get

      $oldAsset = $assets | Where-Object { $_.name -eq "TrendScope.apk" }

      if ($oldAsset) {
        Write-Host "Deleting old APK..."

        Invoke-RestMethod `
          -Headers $headers `
          -Uri "https://api.github.com/repos/$repo/releases/assets/$($oldAsset.id)" `
          -Method Delete
      }

      $finalUploadUrl = "${uploadUrl}?name=TrendScope.apk"

      Write-Host "Final Upload URL: $finalUploadUrl"

      Invoke-RestMethod `
        -Headers @{
          Authorization = "token $env:GITHUB_TOKEN"
          Accept = "application/vnd.github+json"
          "Content-Type" = "application/vnd.android.package-archive"
        } `
        -Uri $finalUploadUrl `
        -Method Post `
        -InFile "apk/TrendScope.apk"

      Write-Host "APK uploaded successfully."